### ISSUE TITLE
[SHORT FUSE] submit abstact for AMS Conference on Environmental Information Processing Technologies (due Sept. 8)

### ISSUE THREAD

**Issue by rabernat** [pangeo-forge/roadmap#32]
Sorry for the very late notice, but I realized tomorrow is the deadline for [AMS2022](https://annual.ametsoc.org/index.cfm/2022/) abstract submission

It would be really great to get a Pangeo Forge abstract submitted to https://annual.ametsoc.org/index.cfm/2022/program-events/conferences-and-symposia/38th-conference-on-environmental-information-processing-technologies/

Three potentially relevant sessions are

> 1. Cloud Computing for Big Data in Atmosphere, Ocean, and Climate (Joint with 21st Conference on Artificial Intelligence for Environmental Science, 12th Symposium on Advances in Modeling and Analysis Using Python, and  the Eighth Symposium on High Performance Computing for Weather, Water, and Climate)
>   Weather imposes constraints on human activity. As a consequence, most decision-makers/planners seek awareness to mitigate or eliminate weather impacts.  As datasets become larger and larger, new and improved tools to work with Big Data are critical.  This session welcomes contributions from research fields such as scientific visualization, information visualization or visual analytics that are applicable to large data sets from climatology, meteorology or related disciplines.  Presentations on using cloud computing for analyzing satellite and model data for weather, ocean, or climate relevant applications will also be welcomed. 
>   This session will showcase solutions for analyzing and processing data from satellites such as GOES-16, GOES-17, Himawari-8, NOAA-20, and NPP while utilizing cloud computing. The NOAA Big Data Program has published years of satellite data into the cloud where it is co-located next to compute resources. Processing of this data can now happen in near real time with push notifications upon arrival of new data or over the entire period of record for satellite reanalysis.
> 
> 2. Developing Cloud-based Tools for Data Analysis and Archiving  (Joint with 21st Conference on Artificial Intelligence for Environmental Science, 12th Symposium on Advances in Modeling and Analysis Using Python, and  the Eighth Symposium on High Performance Computing for Weather, Water, and Climate) 
> Cloud-based technologies continue to evolve and mature in their use and application. This session will delve into the growing use of cloud hosting solutions applied to benefit the environmental sciences and specifically applications for data analysis, visualization and archiving of  environmental information. This session encourages submissions on these topics, focusing on how submitters are incorporating cloud-based applications into their work, what they have done, and what advantages this approach has provided to their efforts.
> 
> 3. FAIR and Open Data and Software within the Atmospheric and Ocean Sciences to Support  Replicable Research and Reusable Tools for Climate Analysis  (Joint with 25th Conference of  Atmospheric Librarians International and the 12th Symposium on Advances in Modeling and Analysis Using Python)
> The need to understand linkages between climatic extremes and security outcomes such as displacement/migration, public health, and food/electricity production has never been higher. Analysis of these linkages requires integration of the Earth, social, economic, and political sciences.   In this session, we invite submissions that discuss projects, initiatives, and ideas that advance community understanding and build upon the principles of FAIR (Findable, Accessible, Interoperable, and Reusable) Open Data and Software within the atmospheric and related sciences. We welcome technical, policy, and community-focused submissions on a range of topics related to facilitating transparency and reproducibility of science, including: data and software discoverability, metadata creation and management, data and metadata formats, provenance tracking, distribution and storage, and other relevant topics.  Platforms for reproducible research and reusable tools will accelerate the analytics enterprise and build the salience, credibility, and legitimacy required to effectively inform policy. This session will highlight emerging open-science tools and platforms for climate-security analysis.

@cisaacstern - how would you feel about recycling your AGU abstract for an AMS submission?

@martindurant, @rsignell-usgs, @lsterzinger - have you made (or are planning) a submission on fsspec-reference-maker?

**Comment by cisaacstern** [comment]
Yes, I can do this first thing tomorrow. HDFReferenceRecipe was not mentioned in the AGU abstract, so I can add that in for this one.

@rwegener2, @jbusecke, and @jhamman: expect another ping on this thread by mid-day PT tomorrow for your approval of this abstract. All of you were co-authors on AGU, so will by default be co-authors on this, unless you prefer otherwise.

I will aim to circulate this as early as possible tomorrow.

**Comment by lsterzinger** [comment]
@rabernat I am not submitting a fsspec-reference-maker abstract to AMS but I have submitted one to AGU

**Comment by martindurant** [comment]
I have a references abstract accepted for PyData Global. I don't know if you can view https://pydata.org/global2021/proposals/153/ , I can paste the MD form.

**Comment by lsterzinger** [comment]
I can't see that, can you paste it?

**Comment by martindurant** [comment]
"All you need is zarr.: Parallel access to remote HDF5, TIFF, grib2 and others."

Summary 

We introduce ReferenceFileSystem, a virtual implementation for fsspec which views arbitrary byte chunks at specific keys, presenting chunks of HDF5, TIFF, grib2 and others at the appropriate paths conforming to zarr's model. Thus, you can use zarr to load data from potentially thousands of remote data files, selecting only what you need, and with parallelism and concurrency. 

Outline 

- the standard formats used for massive data archiving and their shortcomings
- brief introduction to zarr, designed for parallel access to remote data
- the process by which we can expose archival chunks to zarr and aggregate datasets
-  examples of >>10TB datasets where we have done this
 
Description

fsspec's ReferenceFileSystem allows a file system like virtual view onto chunks of bytes stored in arbitrary locations elsewhere, e.g., cloud bucket storage. We can present each byte chunk as a particular path in the filesystem conforming to the zarr hierarchy model, such that the original set of chunks, potentially across many files, appears as a single zarr dataset. This brings the following advantages:
- only zarr (plus the relevant codecs) is required to read the data, but the original data could be locked in HDF5, TIFF or grib2 files (and more to come)
- the metadata is extracted once, so future opening of the dataset does not need to scan through the target files to find metadata, and so the process is much faster
- you get a single logical view over potentially thousands of files, but due to zarr's access model, you only load the data you need
- loading can happen chunk-wise and in parallel

The details of how to make such reference files is described at https://github.com/intake/fsspec-reference-maker , and the latest result for some 80TB/370k files of water flow modelling can be seen at https://nbviewer.jupyter.org/gist/rsignell-usgs/02da7d9257b4b26d84d053be1af2ceeb . Note that this is using xarray to process the data, but only zarr is needed to load it.

**Comment by martindurant** [comment]
(NB: I am the only author on this proposal, but pydata allows you to add authors any time, so I was leaving that until later)

**Comment by cisaacstern** [comment]
@rabernat, instead of the above-listed sessions, how about we submit to: 

> __*12th Symposium on Advances in Modeling and Analysis Using Python*__
**New Python Tools in the Atmospheric and Oceanographic Sciences**
Topic Description: Submissions are welcomed to new Python tools in the atmospheric and oceanographic sciences. Submissions must specifically either introduce new tools or present significant progress (feature additions) to existing tools. If submitters are wishing to present on tool use please submit to other sessions in the Python Symposium.

?

**Comment by rabernat** [comment]
Given the cloud focus of Pangeo Forge, I think that the "Developing Cloud-based Tools for Data Analysis and Archiving" would probably be the most appropriate than the "New Python Tools." But totally your call as the abstract lead.

**Comment by jbusecke** [comment]
FWIW I submitted an abstract to 
> Cloud Computing for Big Data in Atmosphere, Ocean, and Climate (Joint with 21st Conference on Artificial Intelligence for Environmental Science, 12th Symposium on Advances in Modeling and Analysis Using Python, and the Eighth Symposium on High Performance Computing for Weather, Water, and Climate)
Weather imposes constraints on human activity. As a consequence, most decision-makers/planners seek awareness to mitigate or eliminate weather impacts. As datasets become larger and larger, new and improved tools to work with Big Data are critical. This session welcomes contributions from research fields such as scientific visualization, information visualization or visual analytics that are applicable to large data sets from climatology, meteorology or related disciplines. Presentations on using cloud computing for analyzing satellite and model data for weather, ocean, or climate relevant applications will also be welcomed.
This session will showcase solutions for analyzing and processing data from satellites such as GOES-16, GOES-17, Himawari-8, NOAA-20, and NPP while utilizing cloud computing. The NOAA Big Data Program has published years of satellite data into the cloud where it is co-located next to compute resources. Processing of this data can now happen in near real time with push notifications upon arrival of new data or over the entire period of record for satellite reanalysis.

which references pangeo-forge (see text below), but only as part of a more high level workflow. So I would tend to the other session (which @rabernat suggested) to give wide visibility to pangeo efforts across sessions? Happy to coordinate some of the actual presentation details.

Here is the submitted abstract:


# CMIP6 in the cloud - Open, fast and accessible climate science with Pangeo

The Coupled Model Intercomparison Project (CMIP) provides the base on which much of modern climate/earth system science is built. The model output produced is crucial to inform current and future policy decisions about a changing climate due to anthropogenic greenhouse gas emissions.
Continued improvements in computing power,  model development, and scientific understanding of the earth system lead to more and more complex models and rapidly increasing size of output datasets.
Datasets of the current and future generation of global earth system models render the common 'download and analyze' workflow inefficient, blocking innovative analysis and fast scientific discoveries needed to deal with the dramatic changes happening to the planet.

To overcome these limitations, we present a workflow to analyze CMIP6 data in the cloud. Python tools and cloud infrastructure developed within the Pangeo community enables near-instantaneous access and fast data processing to much of the CMIP6 archive with only a web browser. 

The tools presented here demonstrate a wide range of interoperable, efficient, community-based solutions. Starting with analysis-ready cloud optimized data provided by Pangeo-Forge, over labeled dataset representation with `xarray`, parallelized computing with `dask` to specialized solutions to enable easy and fast analysis specifically for CMIP6 data with `cmip6_preprocessing`.
We summarize by demonstrating a complete workflow in which we calculate global surface temperature time series.

**Comment by cisaacstern** [comment]
# Timing

The below-linked abstract is due by 8:59 PM PT / 11:59 PM ET  today. It is now 1:41 PM PT / 1:41 PM ET. To allow everyone a chance to review, but also not cut it too close,
### I will submit at **6 PM PT / 9 PM ET** today.

Any suggestions will be incorporated at that point and anyone who's @'ed below and has either made a suggestion or, alternatively, just read the draft and provided a  👍  on this comment, will be a co-author.

# Draft link

@rabernat, @jbusecke, @rwegener2, @jhamman: [here's a Google Doc with the AMS 2022 draft](https://docs.google.com/document/d/15tmxVHX-UaADuztmDs_qhpd_BHPG_WIdSyA8Gn3cz_k/edit) for your review. Please make edits in Suggesting mode. If you have no edits, just  👍 this comment.

I've provided our AGU abstract below the AMS draft, for reference. AMS allows 1000 words, so I had room to expand on what we'd written for AGU with more detail.

@martindurant, @rsignell-usgs, @lsterzinger: I mention reference maker, so would appreciate your eye to make sure I haven't misrepresented it. And even if you don't have any edits, but would like to be co-authors, please also reply to this comment with 👍 .

Finally (and apologies for the @'ing), if anyone from @pangeo-forge/dev-team would like to be a co-author, also just make sure you agree with the draft (or provide comments), and either way reply to this comment with 👍 . All of you have contributed in one way or another, so specifics edits are not expected for co-authorship.

# Session choice

Based on discussion in this thread, we'll submit to

> Developing Cloud-based Tools for Data Analysis and Archiving (Joint with 21st Conference on Artificial Intelligence for Environmental Science, 12th Symposium on Advances in Modeling and Analysis Using Python, and the Eighth Symposium on High Performance Computing for Weather, Water, and Climate)
Cloud-based technologies continue to evolve and mature in their use and application. This session will delve into the growing use of cloud hosting solutions applied to benefit the environmental sciences and specifically applications for data analysis, visualization and archiving of environmental information. This session encourages submissions on these topics, focusing on how submitters are incorporating cloud-based applications into their work, what they have done, and what advantages this approach has provided to their efforts.

**Comment by lsterzinger** [comment]
For what it's worth, [here is my abstract submitted to AGU ](https://docs.google.com/document/d/1i3bMxnnWVodbAAkuTqcqQGEFuiS9-meJshmh8voSs_g/edit#heading=h.80g89k5vtlke)("Open Science in Action" Session) last month

**Comment by lsterzinger** [comment]
@cisaacstern I worked on fsspec-reference-maker over the summer during an internship with NCAR. I'm not sure what should/shouldn't qualify me for an author spot on your abstract, but I'm happy to have my name on there if appropriate! @rsignell-usgs and @martindurant are the real experts though 😉

**Comment by cisaacstern** [comment]
This abstract has been submitted! 🙌 

All who provided inline comments on the Google Doc and/or 👍 'ed https://github.com/pangeo-forge/roadmap/issues/32#issuecomment-915439859 were listed as co-authors.

Thanks to everyone for rallying together to get this done on such short notice.

**Comment by rabernat** [comment]
Amazing work Charles! Thanks for getting this done so well on a tight timeline.

It will be an awesome meeting, and I'm glad that our project will be well represented.

**Comment by cisaacstern** [comment]
This abstract has been accepted to AMS 2022: https://ams.confex.com/ams/102ANNUAL/meetingapp.cgi/Paper/399850
